# Generated by Django 4.0.3 on 2022-05-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_inventory_type'),
        ('delivery', '0002_rename_delivery_quantity_delivery_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='inventory',
        ),
        migrations.AddField(
            model_name='delivery',
            name='inventory',
            field=models.ManyToManyField(to='dashboard.inventory'),
        ),
    ]
