# Generated by Django 4.0.3 on 2022-05-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_remove_deliveryitem_inventory_deliveryitem_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='quantity',
        ),
    ]
