# Generated by Django 4.0.3 on 2022-05-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_remove_delivery_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryitem',
            name='inventory',
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='specifications',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
