# Generated by Django 4.0.3 on 2022-05-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_remove_deliveryitem_inventory_deliveryitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='specifications',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
