# Generated by Django 4.0.3 on 2022-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_alter_deliveryitem_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=100, null=True),
        ),
    ]
