# Generated by Django 4.0.3 on 2022-04-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_deliveries_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipment',
            new_name='Inventory',
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.RenameField(
            model_name='deliveries',
            old_name='equipment',
            new_name='inventory',
        ),
    ]
