# Generated by Django 4.0.3 on 2022-04-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_equipment_inventory_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.CharField(choices=[('Consummable', 'Consummable'), ('Electrical', 'Electrical'), ('Scrap', 'Scrap'), ('Uniform', 'Uniform'), ('DefBars', 'DefBars'), ('Tools', 'Tools')], max_length=100, null=True),
        ),
    ]
