# Generated by Django 4.0.3 on 2022-05-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_inventory_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
