# Generated by Django 4.0.3 on 2022-05-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_inventory_brand_alter_inventory_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
