# Generated by Django 4.0.3 on 2022-05-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_delete_brand_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(default=1, max_length=100, null=True),
        ),
    ]
