# Generated by Django 4.0.3 on 2022-11-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_type_alter_inventory_status_alter_inventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
