# Generated by Django 4.0.3 on 2022-11-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_inventory_arrived_inventory_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='requested',
            new_name='approved',
        ),
    ]
