# Generated by Django 4.0.3 on 2022-11-07 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_product_stock_remove_inventory_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'Stocks'},
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('NA', 'NA')], max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.brand')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.location')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.type')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
    ]
