# Generated by Django 4.0.3 on 2022-11-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_stock_approved_remove_stock_arrived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverybatches',
            name='items',
        ),
        migrations.AddField(
            model_name='stock',
            name='deliveryID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.deliverybatches'),
            preserve_default=False,
        ),
    ]
