# Generated by Django 4.0.3 on 2022-11-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_deliverybatches_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='Location Instance'),
        ),
    ]
