# Generated by Django 4.0.3 on 2023-01-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_product_location instance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='DeliveryItem',
        ),
        migrations.AlterModelOptions(
            name='deliveryitem',
            options={'verbose_name_plural': 'Delivery Items'},
        ),
    ]
