# Generated by Django 4.0.3 on 2023-02-03 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_rename_stock_deliveryitem_alter_deliveryitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.location')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='deliveryDetails',
        ),
        migrations.DeleteModel(
            name='DeliveryBatches',
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.delivery'),
            preserve_default=False,
        ),
    ]
