# Generated by Django 4.1.6 on 2023-02-15 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_delivery_requestedby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_location',
            new_name='deliveryLocation',
        ),
    ]
