# Generated by Django 4.1.6 on 2023-02-20 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_rename_product_inventory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory Items'},
        ),
    ]
