# Generated by Django 4.1.6 on 2023-02-28 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0032_alter_inventory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=100, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateApproved', models.DateTimeField(blank=True, null=True)),
                ('approvedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_quotations', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quotations',
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventory')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.quotation')),
            ],
            options={
                'verbose_name_plural': 'Quotation Items',
            },
        ),
    ]
