# Generated by Django 4.1.6 on 2023-03-01 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.delivery'),
        ),
    ]
