# Generated by Django 4.0.3 on 2023-03-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_rename_deliveryitems_deliveryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='deliveryitem',
            options={'verbose_name_plural': 'Delivery Items'},
        ),
    ]
