# Generated by Django 4.0.3 on 2023-03-14 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_remove_deliveryitem_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='quotationItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.quotationitem'),
        ),
    ]
