# Generated by Django 4.0.3 on 2023-03-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_remove_deliveryitem_suppliername'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='dateArrived',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
