# Generated by Django 4.0.3 on 2023-03-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_deliveryitem_datearrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approvedDelivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approvedQuotations',
            field=models.BooleanField(default=False),
        ),
    ]
