# Generated by Django 4.0.3 on 2023-03-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_purchaserequest_approveddelivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='deliverySet',
            field=models.BooleanField(default=False),
        ),
    ]
