# Generated by Django 4.1.7 on 2023-03-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0047_inventorywithdrawn"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="restocking_amount",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="restocking_threshold",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
