# Generated by Django 4.0.3 on 2023-05-29 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_purchaserequest_confirmeddeliverycount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialDelivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expectedDeliveryDate', models.DateTimeField(blank=True, null=True)),
                ('dateArrived', models.DateTimeField(blank=True, null=True)),
                ('quantityDelivered', models.PositiveIntegerField(null=True)),
                ('deliveryItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.deliveryitem')),
            ],
            options={
                'verbose_name_plural': 'Delivery Items (Partial)',
            },
        ),
    ]
