# Generated by Django 4.0.3 on 2023-05-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_partialdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='isPartial',
            field=models.BooleanField(default=False),
        ),
    ]
