# Generated by Django 4.0.3 on 2023-05-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_delete_partialdelivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryitem',
            name='isPartial',
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='pQuantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
