# Generated by Django 4.0.3 on 2023-06-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_remove_deliveryitem_ispartial_deliveryitem_pquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='confirmedDeliveryCount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='totalDeliveryCount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
