# Generated by Django 4.0.3 on 2023-06-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_alter_purchaserequest_confirmeddeliverycount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='pQuantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='dateRequested',
            field=models.DateTimeField(blank=True),
        ),
    ]
