# Generated by Django 4.0.3 on 2023-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_alter_deliveryitem_pquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='dateRequested',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
