# Generated by Django 4.0.3 on 2023-06-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_alter_purchaserequest_daterequested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorywithdrawn',
            name='withdrawn_date',
            field=models.DateTimeField(null=True),
        ),
    ]
