# Generated by Django 4.0.3 on 2023-06-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_alter_inventorywithdrawn_withdrawn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorywithdrawn',
            name='withdrawn_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
