# Generated by Django 4.0.3 on 2023-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_alter_inventorywithdrawn_withdrawn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='pQuantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='confirmedDeliveryCount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='totalDeliveryCount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
