# Generated by Django 4.0.3 on 2023-07-01 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0060_alter_deliveryitem_pquantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorydamaged',
            options={'verbose_name_plural': 'Damaged Inventory Items'},
        ),
        migrations.AlterModelOptions(
            name='inventoryreturned',
            options={'verbose_name_plural': 'Transferred Inventory Items'},
        ),
        migrations.AlterField(
            model_name='inventoryreturned',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_inventory_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryreturned',
            name='transferredTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_inventory_location', to='dashboard.location'),
        ),
    ]
