# Generated by Django 4.0.3 on 2023-07-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_inventoryrecount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryrecount',
            old_name='quantity',
            new_name='oQuantity',
        ),
        migrations.AddField(
            model_name='inventoryrecount',
            name='rQuantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
