# Generated by Django 4.0.3 on 2023-07-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_rename_quantity_inventoryrecount_oquantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='inventoryrecount',
            options={'verbose_name_plural': 'Recounted Inventory Log'},
        ),
        migrations.RenameField(
            model_name='quotationitem',
            old_name='price',
            new_name='totalPrice',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='methodOfPayment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='pricePerUnit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.supplier')),
            ],
        ),
    ]
