# Generated by Django 4.0.3 on 2023-07-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_supplier_alter_inventoryrecount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='isRejected',
            field=models.BooleanField(default=False),
        ),
    ]
