# Generated by Django 4.0.3 on 2023-07-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_quotationitem_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='pricePerUnit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
