# Generated by Django 4.0.3 on 2023-07-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_alter_quotationitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieritem',
            name='dateApproved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
